#!/usr/bin/env bash
# Regenerates every Blender-authored asset from source scripts.
#
#   ./scripts/build_assets.sh
#
# All art in this project is generated headlessly from Python. A hand-edited
# .blend that cannot be reproduced from a script is treated as a bug: proportions
# and level kit dimensions change constantly while movement is being tuned, and an
# asset that can only be regenerated by hand becomes the thing nobody dares touch.

source "$(dirname "$0")/lib.sh"

command -v blender >/dev/null 2>&1 \
  || die "blender not found. See docs/ENVIRONMENT.md (it needs mesa-libGL even headless)."

step "Blender: $(blender --version 2>/dev/null | head -1)"

CHAR_DIR="$GAME_DIR/assets/characters"
LOG_DIR="$REPO_ROOT/exports/tmp"
mkdir -p "$CHAR_DIR" "$LOG_DIR"

# --- character ----------------------------------------------------------------
step "Building runner character"
LOG="$LOG_DIR/build_runner.log"
set +e
blender --background --factory-startup \
  --python "$REPO_ROOT/blender/scripts/build_runner.py" \
  -- --out "$CHAR_DIR" >"$LOG" 2>&1
status=$?
set -e

# Blender exits 0 on a Python exception in some paths, so the explicit success
# marker printed by the script is the real signal.
if ! grep -q '^BUILD_RUNNER: DONE' "$LOG"; then
  tail -40 "$LOG" >&2
  die "runner build failed (exit $status) — see $LOG"
fi
grep -E '^\[build_runner\]' "$LOG" | sed 's/^/  /'

[ -s "$CHAR_DIR/runner.glb" ] || die "runner.glb was not written"
ok "runner.glb  $(du -h "$CHAR_DIR/runner.glb" | cut -f1)"

# --- environment kit ----------------------------------------------------------
PROP_DIR="$GAME_DIR/assets/props"
mkdir -p "$PROP_DIR"

step "Building environment kit"
KIT_LOG="$LOG_DIR/build_kit.log"
set +e
blender --background --factory-startup \
  --python "$REPO_ROOT/blender/scripts/build_kit.py" \
  -- --out "$PROP_DIR" >"$KIT_LOG" 2>&1
kit_status=$?
set -e

if ! grep -q '^BUILD_KIT: DONE' "$KIT_LOG"; then
  tail -40 "$KIT_LOG" >&2
  die "kit build failed (exit $kit_status) — see $KIT_LOG"
fi
grep -E '^\[build_kit\]' "$KIT_LOG" | sed 's/^/  /'

prop_count=$(ls -1 "$PROP_DIR"/*.glb 2>/dev/null | wc -l)
[ "$prop_count" -gt 0 ] || die "no props were written"
ok "$prop_count props  $(du -sh "$PROP_DIR" | cut -f1)"

# --- reimport so Godot picks up the new meshes --------------------------------
step "Refreshing Godot import cache"
GODOT="$(find_godot)"
export GODOT_SILENCE_ROOT_WARNING=1
"$GODOT" --headless --path "$GAME_DIR" --import >"$LOG_DIR/asset_import.log" 2>&1 || true
assert_no_godot_errors "$LOG_DIR/asset_import.log"
ok "imported"

printf '\n%sAssets rebuilt.%s\n' "$C_GREEN$C_BOLD" "$C_OFF"
